plugins {
    id "net.fabricmc.fabric-loom-remap"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    compileOnly "org.spongepowered:mixin:${mixin_version}"
}

sourceSets.main {
    java.srcDirs project(":common").file("src/main/java"), "src/itemEditorApi/java"
    resources.srcDir project(":common").file("src/main/resources")
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/1.21.11-client")
        }
    }
}

tasks.named("jar") { archiveClassifier = "dev" }

tasks.withType(Jar).configureEach {
    exclude "me/noramibu/itemeditor/api/**"
}
