plugins {
    id "com.gradleup.shadow"
    id "net.fabricmc.fabric-loom-remap"
}

configurations { faststats }

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation files(configurations.faststats)
    compileOnly "org.spongepowered:mixin:${mixin_version}"

    faststats("dev.faststats.metrics:fabric:0.27.3-pre2+mc1.21.9-1.21.11") { transitive = false }
}

sourceSets.main {
    java.srcDirs project(":common").file("src/main/java"), "src/itemEditorApi/java"
    resources.srcDir project(":common").file("src/main/resources")
}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/1.21.11-client")
        }
    }
}

tasks.named("shadowJar") {
    archiveClassifier = "dev-shadow"
    configurations = [project.configurations.faststats]
    relocate "dev.faststats", "me.noramibu.lumentooltips.lib.faststats"
    mergeServiceFiles()
    exclude "module-info.class"
}

tasks.named("remapJar") {
    dependsOn tasks.named("shadowJar")
    inputFile.set(tasks.named("shadowJar").flatMap { it.archiveFile })
    archiveClassifier = ""
}

tasks.named("jar") { archiveClassifier = "dev" }

tasks.withType(Jar).configureEach {
    exclude "me/noramibu/itemeditor/api/**"
}
