org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=lumen_tooltips
mod_name=Lumen Tooltips
commmod_version=b2
artifact_minecraft_version=1.21.11
mod_group=me.noramibu.lumentooltips
mod_author=noramibu
mod_license=GPL-3.0-only
mod_description=Clear item tooltip information with built-in configuration.

java_version=21
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
fabric_minecraft_version=~1.21.11
neoform_version=1.21.11-20251209.172050
neoforge_version=21.11.42
neoforge_version_range=[21.11,21.12)
fabric_loader_version=0.19.0
fabric_api_version=0.141.4+1.21.11
fabric_loom_version=1.17.14
moddev_version=2.0.141
mixin_version=0.8.7
