org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=lumen_tooltips
mod_name=Lumen Tooltips
mod_version=6
artifact_minecraft_version=26.2
mod_group=me.noramibu.lumentooltips
mod_author=noramibu
mod_license=GPL-3.0-only
mod_description=Clear item tooltip information with built-in configuration.

java_version=25
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
fabric_minecraft_version=~26.2
neoform_version=26.2-2
neoforge_version=26.2.0.76
neoforge_version_range=[26.2,)
fabric_loader_version=0.19.3
fabric_loom_version=1.15.5
fabric_api_version=0.152.1+26.2
moddev_version=2.0.141
mixin_version=0.8.7
